export default function ZoeAbout() {
  return (
    <section id="about" className="py-24 bg-stone-950">
      <div className="max-w-3xl mx-auto px-6 text-center">
        <p className="text-amber-200/60 text-xs tracking-[0.3em] uppercase mb-4">
          About Zoe
        </p>
        <h2 className="font-serif text-3xl sm:text-4xl text-amber-50 mb-8">
          The Name Means Life
        </h2>
        <div className="space-y-6 text-stone-400 leading-relaxed">
          <p>
            Zoe was born from a simple observation: scent is the most emotionally
            powerful sense we have — the only one with a direct neural pathway to
            memory and emotion — and yet no one has built a platform that treats
            it with the depth it deserves.
          </p>
          <p>
            We believe your fragrance should be as unique as your fingerprint. Not
            chosen from a shelf. Not recommended by an algorithm that knows nothing
            about the smell of your grandmother&apos;s kitchen or the sound of rain
            on a cabin roof that makes you feel at home.
          </p>
          <p>
            Every Zoe fragrance is a genuine Eau de Parfum — 15–18% concentration,
            crafted by an experienced perfumer, from a creative brief generated by
            the most detailed preference mapping ever applied to scent. It is real
            perfumery. It just starts with you instead of a boardroom.
          </p>
          <p className="text-amber-200/60 italic font-serif text-lg">
            Your scent. Your story. Getting more precise with every wear.
          </p>
        </div>
      </div>
    </section>
  )
}
